### ISSUE TITLE
Problem Running in OMNeT++ IDE

### ISSUE THREAD

**Issue by PedroSantos21** [ThomDietrich/multiUAV-simulation#55]
Hi,

I just found the project and I  followed all the steps mentioned in README but now I'm facing a problem executing one of the predefined run and debug configurations. When I execute a got this error message:

**MobileNode.h:23:10: fatal error: osgEarthUtil/ObjectLocator: No such file or directory**

Not only in this file but also in others. Anyone has faced the same problem?

**Comment by ThomDietrich** [comment]
No sorry not sure what happened.

If you figure out what is wrong, please consider sharing your solution!

**Comment by PedroSantos21** [comment]
> No sorry not sure what happened.
> 
> If you figure out what is wrong, please consider sharing your solution!


I already solved that. Them problem was that, as I'm running on Ubuntu 18.04, there were some compatibility problems with the osgEarth library, so I had to build it that by myself. But still, I'm unable to fully execute the project and the examples. There is some step-by-step tutorial that I could follow? I'm sorry if this is a dummy question, but I am quite new using OMNeT++.

**Comment by ThomDietrich** [comment]
You should try the various osgEarth examples first. After they are running our project should work as well.

**Comment by PedroSantos21** [comment]
Ok. Now I'm having a problem with osgEarthUtil/ObjectLocator that become deprecated since osgEarth 2.9 and now was replaced by GeoTransform. Which version of osgEarth the project is based on?

**Comment by ThomDietrich** [comment]
It should work with omnet 5.4, maybe try with this first?

**Comment by PedroSantos21** [comment]
Ok... I tried with the OMNeT 5.4, and followed all the steps of the installation guide. Still, the project presents several errors, some osgEarth methods and classes seem to be deprecated. In OMNeT installation, it is recommended osgEarth 2.7 or later. To this project, there is some specific version of osgEarth? And is there some requirements file with all dependencies of the project?

Thanks for your help.
